// ──────────────────────────────────────────────
// Triage Combat — fixed content catalog
// ──────────────────────────────────────────────
// Hand-authored once: the real-world ATLS-flavored toolkit and the closed list
// of possible diagnoses. The LLM never invents these — only which differential
// is correct for a given case (see TriageCaseSeed in types.ts).

import type { TriageActionDef, TriageDifferentialDef } from "./types.js";

export const DIFFERENTIAL_CATALOG: readonly TriageDifferentialDef[] = [
  { id: "tension_pneumo", name: "Tension Pneumothorax" },
  { id: "hemorrhagic_shock", name: "Hemorrhagic Shock" },
  { id: "cardiac_tamponade", name: "Cardiac Tamponade" },
  { id: "neurogenic_shock", name: "Neurogenic Shock" },
  { id: "septic_shock", name: "Septic Shock" },
  { id: "pulmonary_embolism", name: "Pulmonary Embolism" },
  { id: "opioid_od", name: "Opioid Overdose" },
  { id: "hypoglycemia", name: "Hypoglycemia" },
  { id: "ich", name: "Intracranial Hemorrhage" },
  { id: "anaphylaxis", name: "Anaphylaxis" },
  { id: "dka", name: "Diabetic Ketoacidosis" },
  { id: "massive_hemothorax", name: "Massive Hemothorax" },
  { id: "aortic_dissection", name: "Aortic Dissection" },
  { id: "status_epilepticus", name: "Status Epilepticus" },
  { id: "tca_overdose", name: "TCA Overdose" },
  { id: "hyperkalemia", name: "Hyperkalemia" },
];

export function differentialName(id: string): string {
  return DIFFERENTIAL_CATALOG.find((d) => d.id === id)?.name ?? id;
}

/** Always available every round — generic ATLS primary-survey support, never tied to a specific differential. */
export const BASELINE_ACTION_IDS: readonly string[] = ["bvm_intubate", "bolus_fluids", "push_epi"];

export const ACTION_CATALOG: readonly TriageActionDef[] = [
  // ── Instant, generic supportive (not tied to one differential) ──
  {
    id: "bvm_intubate",
    name: "BVM / Intubate",
    category: "airway",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Secure the airway and support ventilation.",
    vitalEffects: { spo2: 6, gcs: 1 },
  },
  {
    id: "bolus_fluids",
    name: "Bolus IV Fluids",
    category: "circulation",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Push a crystalloid bolus to support perfusion.",
    vitalEffects: { map: 6 },
    crashDelta: -3,
  },
  {
    id: "push_epi",
    name: "Push IV Epinephrine",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "A short-acting pressor to buy time while the real cause is addressed.",
    vitalEffects: { map: 8 },
    crashDelta: -3,
  },

  // ── Instant, definitive treatments (one per differential) ──
  {
    id: "needle_decompression",
    name: "Needle Decompression",
    category: "breathing",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Emergent decompression of a tension pneumothorax.",
    treatsDifferentialId: "tension_pneumo",
    vitalEffects: { spo2: 10, map: 8 },
    crashDelta: -30,
  },
  {
    id: "call_or_laparotomy",
    name: "Call OR: Emergent Laparotomy",
    category: "circulation",
    speed: "instant",
    apCost: 2,
    latencyRounds: 0,
    description: "Get the bleeding source under a surgeon's control.",
    treatsDifferentialId: "hemorrhagic_shock",
    vitalEffects: { map: 10 },
    crashDelta: -30,
  },
  {
    id: "pericardiocentesis",
    name: "Pericardiocentesis",
    category: "circulation",
    speed: "instant",
    apCost: 2,
    latencyRounds: 0,
    description: "Needle aspiration of pericardial fluid compressing the heart.",
    treatsDifferentialId: "cardiac_tamponade",
    vitalEffects: { map: 10 },
    crashDelta: -30,
  },
  {
    id: "vasopressors",
    name: "Start Vasopressors",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Restore vascular tone lost to spinal cord injury.",
    treatsDifferentialId: "neurogenic_shock",
    vitalEffects: { map: 10 },
    crashDelta: -30,
  },
  {
    id: "broad_spectrum_abx",
    name: "Broad-Spectrum Antibiotics + Pressors",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Source control and hemodynamic support for sepsis.",
    treatsDifferentialId: "septic_shock",
    vitalEffects: { map: 8, spo2: 4 },
    crashDelta: -30,
  },
  {
    id: "thrombolysis",
    name: "Thrombolysis / Anticoagulation",
    category: "drugs",
    speed: "instant",
    apCost: 2,
    latencyRounds: 0,
    description: "Break up the clot obstructing pulmonary circulation.",
    treatsDifferentialId: "pulmonary_embolism",
    vitalEffects: { spo2: 10, map: 6 },
    crashDelta: -30,
  },
  {
    id: "naloxone",
    name: "Push Naloxone",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Reverse opioid-induced respiratory depression.",
    treatsDifferentialId: "opioid_od",
    vitalEffects: { spo2: 12, gcs: 3 },
    crashDelta: -30,
  },
  {
    id: "d50_dextrose",
    name: "Push D50 Dextrose",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Correct severe hypoglycemia.",
    treatsDifferentialId: "hypoglycemia",
    vitalEffects: { gcs: 4 },
    crashDelta: -30,
  },
  {
    id: "neurosurgery_call",
    name: "Neurosurgery Call + Osmotic Therapy",
    category: "drugs",
    speed: "instant",
    apCost: 2,
    latencyRounds: 0,
    description: "Reduce intracranial pressure and get neurosurgery involved.",
    treatsDifferentialId: "ich",
    vitalEffects: { gcs: 3 },
    crashDelta: -30,
  },
  {
    id: "im_epi_antihistamine",
    name: "IM Epi + Antihistamine/Steroid",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Reverse the airway swelling and vascular collapse of anaphylaxis.",
    treatsDifferentialId: "anaphylaxis",
    vitalEffects: { spo2: 8, map: 8 },
    crashDelta: -30,
  },
  {
    id: "iv_fluids_insulin",
    name: "IV Fluids + Insulin Drip",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Correct the dehydration and acidosis of diabetic ketoacidosis.",
    treatsDifferentialId: "dka",
    vitalEffects: { map: 6, gcs: 2 },
    crashDelta: -30,
  },
  {
    id: "chest_tube_thoracostomy",
    name: "Chest Tube Thoracostomy",
    category: "breathing",
    speed: "instant",
    apCost: 2,
    latencyRounds: 0,
    description: "Evacuate blood filling the pleural space.",
    treatsDifferentialId: "massive_hemothorax",
    vitalEffects: { spo2: 8, map: 6 },
    crashDelta: -30,
  },
  {
    id: "vascular_surgery_call",
    name: "Vascular Surgery: Emergent Repair",
    category: "circulation",
    speed: "instant",
    apCost: 2,
    latencyRounds: 0,
    description: "Get a dissecting aorta under surgical control before it ruptures.",
    treatsDifferentialId: "aortic_dissection",
    vitalEffects: { map: 8 },
    crashDelta: -30,
  },
  {
    id: "iv_benzodiazepine",
    name: "IV Benzodiazepine",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Break the seizure before it causes lasting harm.",
    treatsDifferentialId: "status_epilepticus",
    vitalEffects: { gcs: 3 },
    crashDelta: -30,
  },
  {
    id: "sodium_bicarbonate",
    name: "Sodium Bicarbonate",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Counter the sodium-channel blockade of TCA overdose.",
    treatsDifferentialId: "tca_overdose",
    vitalEffects: { map: 6 },
    crashDelta: -30,
  },
  {
    id: "calcium_gluconate_insulin_glucose",
    name: "Calcium Gluconate + Insulin/Glucose",
    category: "drugs",
    speed: "instant",
    apCost: 1,
    latencyRounds: 0,
    description: "Stabilize the heart and shift potassium back into cells.",
    treatsDifferentialId: "hyperkalemia",
    vitalEffects: { map: 4, gcs: 1 },
    crashDelta: -30,
  },

  // ── Bedside diagnostics (1-round latency) ──
  {
    id: "fingerstick_glucose",
    name: "Fingerstick Glucose",
    category: "diagnostics",
    speed: "bedside",
    apCost: 1,
    latencyRounds: 1,
    description: "Rules coma-causing hypoglycemia in or out fast.",
    diagnosesDifferentialIds: ["hypoglycemia", "dka"],
  },
  {
    id: "efast_ultrasound",
    name: "eFAST Ultrasound",
    category: "diagnostics",
    speed: "bedside",
    apCost: 2,
    latencyRounds: 1,
    description: "Checks pericardium, abdomen, and pleura for free fluid or air.",
    diagnosesDifferentialIds: ["hemorrhagic_shock", "cardiac_tamponade", "tension_pneumo", "massive_hemothorax"],
  },
  {
    id: "abg",
    name: "Point-of-Care ABG",
    category: "diagnostics",
    speed: "bedside",
    apCost: 1,
    latencyRounds: 1,
    description: "Acid-base and oxygenation picture — hints at sepsis, PE, or DKA.",
    diagnosesDifferentialIds: ["septic_shock", "pulmonary_embolism", "dka"],
  },
  {
    id: "pupil_check",
    name: "Pupil / Neuro Check",
    category: "diagnostics",
    speed: "bedside",
    apCost: 1,
    latencyRounds: 1,
    description: "Pinpoint pupils vs. blown pupil — classic differentiator.",
    diagnosesDifferentialIds: ["opioid_od", "ich"],
  },
  {
    id: "skin_airway_exam",
    name: "Skin / Airway Exam",
    category: "diagnostics",
    speed: "bedside",
    apCost: 1,
    latencyRounds: 1,
    description: "Hives, swelling, and stridor point straight at anaphylaxis.",
    diagnosesDifferentialIds: ["anaphylaxis"],
  },
  {
    id: "bedside_neuro_exam",
    name: "Bedside Neuro Exam",
    category: "diagnostics",
    speed: "bedside",
    apCost: 1,
    latencyRounds: 1,
    description: "Witnessed convulsive activity and post-ictal state.",
    diagnosesDifferentialIds: ["status_epilepticus"],
  },
  {
    id: "ecg_monitor",
    name: "12-Lead ECG",
    category: "diagnostics",
    speed: "bedside",
    apCost: 1,
    latencyRounds: 1,
    description: "Widened QRS or peaked T waves — a toxidrome or electrolyte problem.",
    diagnosesDifferentialIds: ["tca_overdose", "hyperkalemia"],
  },

  // ── Formal labs/imaging (2-3 round latency) ──
  {
    id: "type_and_crossmatch",
    name: "Type & Crossmatch",
    category: "diagnostics",
    speed: "formal",
    apCost: 1,
    latencyRounds: 2,
    description: "Formal blood bank workup for active hemorrhage.",
    diagnosesDifferentialIds: ["hemorrhagic_shock"],
  },
  {
    id: "chest_pelvis_xray",
    name: "Chest / Pelvis X-Ray",
    category: "diagnostics",
    speed: "formal",
    apCost: 1,
    latencyRounds: 2,
    description: "Screens for pneumothorax and pelvic fracture as a bleeding source.",
    diagnosesDifferentialIds: ["tension_pneumo", "hemorrhagic_shock", "massive_hemothorax", "aortic_dissection"],
  },
  {
    id: "ct_panscan",
    name: "CT Pan-Scan",
    category: "diagnostics",
    speed: "formal",
    apCost: 2,
    latencyRounds: 3,
    description: "The definitive full-body look — but the patient is off the floor while it runs.",
    diagnosesDifferentialIds: ["ich", "pulmonary_embolism", "cardiac_tamponade", "septic_shock", "aortic_dissection"],
    confirmsOnResolve: true,
    requiresStablePatient: true,
  },
];

export function actionById(id: string): TriageActionDef | undefined {
  return ACTION_CATALOG.find((a) => a.id === id);
}
